sudo: false
language: ruby
rvm:
  - 2.3.1
  - 2.2
  - 2.4.0-preview1
matrix:
  allow_failures:
  - rvm: 2.4.0-preview1

before_install: gem install bundler -v 1.12.5
script: bundle exec rake spec SPEC_OPTS="--format p"
addons:
  code_climate:
    repo_token: b4319eb676f021fb9473aa342324abd74f58d146e174f3cdf57f103bab052f25
