sudo: false
language: ruby
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
env:
  - RUST=yes
  - RUST=no

before_install:
  - if [[ "$RUST" == "yes" ]]; then curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable; export PATH="$HOME/.cargo/bin:$PATH"; fi

script:
  - if [[ "$RUST" == "yes" ]]; then bundle exec rake SPEC_OPTS="--format p"; else bundle exec rake spec SPEC_OPTS="--format p"; fi
