sudo: false
language: ruby
rvm:
  - 2.3.3
  - 2.2
  - 2.4.0-preview3
matrix:
  allow_failures:
  - rvm: 2.4.0-preview3

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
  - gem install bundler -v 1.13.6
script: bundle exec rake SPEC_OPTS="--format p"
addons:
  code_climate:
    repo_token: b4319eb676f021fb9473aa342324abd74f58d146e174f3cdf57f103bab052f25
