[package]
name = "rusty_sanscript"
version = "0.4.1"
authors = ["Tim Bellefleur <nomoon@phoebus.ca>"]
publish = false

[dependencies]
lazy_static = "^0.2.10"
ruby-sys = "^0.3.0"
regex = "^0.2.2"

[lib]
crate-type = ["cdylib"]
