[package]
name = "rusty_sanscript"
version = "0.4.1"
authors = ["Tim Bellefleur <nomoon@phoebus.ca>"]
publish = false

[dependencies]
lazy_static = "^0.2.4"
ruby-sys = "^0.2.20"
regex = "^0.2.1"

[lib]
crate-type = ["cdylib"]
