[package]
name = "rusty_sanscript"
version = "0.3.0"
authors = ["Tim Bellefleur <nomoon@phoebus.ca>"]
publish = false

[dependencies]
lazy_static = "^0.2.2"
ruby-sys = "^0.2.17"
regex = "^0.1.80"

[lib]
crate-type = ["cdylib"]
