[package]
name = "rusty_sanscript"
version = "0.3.0"
authors = ["Tim Bellefleur <nomoon@phoebus.ca>"]
publish = false

[dependencies]
lazy_static = "^0.2.1"
ruby-sys = "^0.2.13"
regex = "^0.1.77"

[lib]
crate-type = ["cdylib"]
